// <auto-generated />
using System;
using Cashly.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cashly.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241005063357_DataSeedingForExample")]
    partial class DataSeedingForExample
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cashly.Server.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 33265,
                            Amount = 24.68m,
                            Category = "Fun",
                            Date = new DateOnly(2024, 9, 6),
                            Title = "Electricity Bill",
                            UserId = 7
                        },
                        new
                        {
                            Id = 15527,
                            Amount = 74.25m,
                            Category = "Fun",
                            Date = new DateOnly(2024, 9, 7),
                            Title = "Electricity Bill",
                            UserId = 7
                        },
                        new
                        {
                            Id = 51620,
                            Amount = 76.52m,
                            Category = "Shopping",
                            Date = new DateOnly(2024, 9, 8),
                            Title = "Dining Out",
                            UserId = 7
                        },
                        new
                        {
                            Id = 57859,
                            Amount = 97.84m,
                            Category = "Shopping",
                            Date = new DateOnly(2024, 9, 9),
                            Title = "Internet",
                            UserId = 7
                        },
                        new
                        {
                            Id = 16055,
                            Amount = 92.32m,
                            Category = "Shopping",
                            Date = new DateOnly(2024, 9, 10),
                            Title = "Electricity Bill",
                            UserId = 7
                        },
                        new
                        {
                            Id = 9476,
                            Amount = 34.77m,
                            Category = "Fun",
                            Date = new DateOnly(2024, 9, 11),
                            Title = "Dining Out",
                            UserId = 7
                        },
                        new
                        {
                            Id = 39519,
                            Amount = 31.79m,
                            Category = "Fun",
                            Date = new DateOnly(2024, 9, 12),
                            Title = "Electricity Bill",
                            UserId = 7
                        },
                        new
                        {
                            Id = 4229,
                            Amount = 80.52m,
                            Category = "Utility",
                            Date = new DateOnly(2024, 9, 13),
                            Title = "Electricity Bill",
                            UserId = 7
                        },
                        new
                        {
                            Id = 97546,
                            Amount = 62.57m,
                            Category = "Food",
                            Date = new DateOnly(2024, 9, 14),
                            Title = "Dining Out",
                            UserId = 7
                        },
                        new
                        {
                            Id = 17189,
                            Amount = 17.33m,
                            Category = "Fun",
                            Date = new DateOnly(2024, 9, 15),
                            Title = "Electricity Bill",
                            UserId = 7
                        },
                        new
                        {
                            Id = 4442,
                            Amount = 54.66m,
                            Category = "Food",
                            Date = new DateOnly(2024, 9, 16),
                            Title = "Fuel",
                            UserId = 7
                        },
                        new
                        {
                            Id = 98779,
                            Amount = 41.14m,
                            Category = "Fun",
                            Date = new DateOnly(2024, 9, 17),
                            Title = "Groceries",
                            UserId = 7
                        },
                        new
                        {
                            Id = 49940,
                            Amount = 43.07m,
                            Category = "Food",
                            Date = new DateOnly(2024, 9, 18),
                            Title = "Fuel",
                            UserId = 7
                        },
                        new
                        {
                            Id = 20442,
                            Amount = 85.60m,
                            Category = "Utility",
                            Date = new DateOnly(2024, 9, 19),
                            Title = "Dining Out",
                            UserId = 7
                        },
                        new
                        {
                            Id = 5694,
                            Amount = 0.12m,
                            Category = "Utility",
                            Date = new DateOnly(2024, 9, 20),
                            Title = "Internet",
                            UserId = 7
                        },
                        new
                        {
                            Id = 98319,
                            Amount = 27.11m,
                            Category = "Utility",
                            Date = new DateOnly(2024, 9, 21),
                            Title = "Internet",
                            UserId = 7
                        },
                        new
                        {
                            Id = 87276,
                            Amount = 63.76m,
                            Category = "Shopping",
                            Date = new DateOnly(2024, 9, 22),
                            Title = "Groceries",
                            UserId = 7
                        },
                        new
                        {
                            Id = 75424,
                            Amount = 2.51m,
                            Category = "Food",
                            Date = new DateOnly(2024, 9, 23),
                            Title = "Fuel",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8058,
                            Amount = 52.57m,
                            Category = "Shopping",
                            Date = new DateOnly(2024, 9, 24),
                            Title = "Shopping",
                            UserId = 7
                        },
                        new
                        {
                            Id = 7939,
                            Amount = 44.86m,
                            Category = "Utility",
                            Date = new DateOnly(2024, 9, 25),
                            Title = "Dining Out",
                            UserId = 7
                        },
                        new
                        {
                            Id = 79801,
                            Amount = 8.30m,
                            Category = "Food",
                            Date = new DateOnly(2024, 9, 26),
                            Title = "Internet",
                            UserId = 7
                        },
                        new
                        {
                            Id = 74632,
                            Amount = 57.73m,
                            Category = "Fun",
                            Date = new DateOnly(2024, 9, 27),
                            Title = "Electricity Bill",
                            UserId = 7
                        },
                        new
                        {
                            Id = 37699,
                            Amount = 62.27m,
                            Category = "Other",
                            Date = new DateOnly(2024, 9, 28),
                            Title = "Internet",
                            UserId = 7
                        },
                        new
                        {
                            Id = 65913,
                            Amount = 92.20m,
                            Category = "Shopping",
                            Date = new DateOnly(2024, 9, 29),
                            Title = "Shopping",
                            UserId = 7
                        },
                        new
                        {
                            Id = 63140,
                            Amount = 36.26m,
                            Category = "Food",
                            Date = new DateOnly(2024, 9, 30),
                            Title = "Electricity Bill",
                            UserId = 7
                        },
                        new
                        {
                            Id = 63233,
                            Amount = 7.36m,
                            Category = "Shopping",
                            Date = new DateOnly(2024, 10, 1),
                            Title = "Internet",
                            UserId = 7
                        },
                        new
                        {
                            Id = 7777,
                            Amount = 60.25m,
                            Category = "Other",
                            Date = new DateOnly(2024, 10, 2),
                            Title = "Internet",
                            UserId = 7
                        },
                        new
                        {
                            Id = 52750,
                            Amount = 94.72m,
                            Category = "Utility",
                            Date = new DateOnly(2024, 10, 3),
                            Title = "Gym Membership",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8962,
                            Amount = 4.20m,
                            Category = "Other",
                            Date = new DateOnly(2024, 10, 4),
                            Title = "Electricity Bill",
                            UserId = 7
                        },
                        new
                        {
                            Id = 45448,
                            Amount = 73.74m,
                            Category = "Food",
                            Date = new DateOnly(2024, 10, 5),
                            Title = "Groceries",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Cashly.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cashly.Server.Models.Expense", b =>
                {
                    b.HasOne("Cashly.Server.Models.User", null)
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cashly.Server.Models.User", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
